### ISSUE TITLE
Weird Raptor HTML table produced for FF+tabulator

### ISSUE THREAD

**Issue by timbl** [linkeddata/gold#11]
Accessing the root of a new gold srever using  Firefox with tabulator, or

curl -k -H "Accept:text/xml,application/xml,application/xhtml+xml,text/html;q=0.5,text/plain,image/png,*/*;q=0.1,application/rdf+xml,text/n3,text/turtle

produces a plain HTML table instead of the   RDF which should be given, (assuming the resource is primarily a data resource.)

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
        "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Raptor Graph Serialisation</title>
</head>
<body>
  <table id="triples" border="1">
    <tr>
      <th>Subject</th>
      <th>Predicate</th>
      <th>Object</th>
    </tr>
    <tr class="triple">
      <td><span class="uri"><a href="https://localhost:9999/">https://localhost:9999/</a></span></td>
      <td><span class="uri"><a href="http://www.w3.org/1999/02/22-rdf-syntax-ns#type">http://www.w3.org/1999/02/22-rdf-syntax-ns#type</a></span></td>
      <td><span class="uri"><a href="http://www.w3.org/ns/posix/stat#Directory">http://www.w3.org/ns/posix/stat#Directory</a></span></td>
    </tr>
    <tr class="triple">
      <td><span class="uri"><a href="https://localhost:9999/">https://localhost:9999/</a></span></td>
      <td><span class="uri"><a href="http://www.w3.org/1999/02/22-rdf-syntax-ns#type">http://www.w3.org/1999/02/22-rdf-syntax-ns#type</a></span></td>
      <td><span class="uri"><a href="http://www.w3.org/ns/ldp#BasicContainer">http://www.w3.org/ns/ldp#BasicContainer</a></span></td>
    </tr>
    <tr class="triple">
      <td><span class="uri"><a href="https://localhost:9999/">https://localhost:9999/</a></span></td>
      <td><span class="uri"><a href="http://www.w3.org/ns/posix/stat#mtime">http://www.w3.org/ns/posix/stat#mtime</a></span></td>
      <td><span class="literal"><span class="value">1407521961</span></span></td>
    </tr>
    <tr class="triple">
      <td><span class="uri"><a href="https://localhost:9999/">https://localhost:9999/</a></span></td>
      <td><span class="uri"><a href="http://www.w3.org/ns/posix/stat#size">http://www.w3.org/ns/posix/stat#size</a></span></td>
      <td><span class="literal"><span class="value">68</span></span></td>
    </tr>
  </table>
  <p>Total number of triples: <span class="count">4</span>.</p>
</body>
</html>

**Comment by deiu** [comment]
It seems application/xhtml+xml is the cause.
