### ISSUE TITLE
Statistics page for tracking e.g number of users

### ISSUE THREAD

**Issue by timbl** [linkeddata/gold#38]
It would be good to have (by default) a public page on gold which gives some anonymous stats like the number of users, mean and median  number of triples/user, so we can see ho things grow. 

 And link it maybe to and from a  master list of gold installations (until there a million)

**Comment by dmitrizagidulin** [comment]
Moving to https://github.com/solid/solid/issues/6 as a result of the [solid project workflow discussion](https://github.com/solid/solid-spec/issues/75). Closing.
