### ISSUE TITLE
Crash when adding : <>  <> """"1""""  . 

### ISSUE THREAD

**Issue by melvincarvalho** [linkeddata/gold#40]
This is causing a server crash for me when I run gold in the cloud, latest version

It works locally for me tho

I'll investigate further, but would be interested to know if anyone else can replicate this by uploading that triple to a file.

**Comment by melvincarvalho** [comment]
Running Ubuntu 14.04 on EC2, stack trace:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x0]

goroutine 3886 [running]:
github.com/presbrey/goraptor.GoRaptor_handle_log(0xc208166040, 0x7fd4040031c0)
	/home/ubuntu/go/src/github.com/presbrey/goraptor/goraptor.go:698 +0x68
github.com/presbrey/goraptor._Cfunc_raptor_parser_parse_chunk(0x7fd404072990, 0x0, 0x0, 0x1, 0x0)
	/home/ubuntu/go/src/github.com/presbrey/goraptor/:202 +0x43
github.com/presbrey/goraptor.func·011()
	/home/ubuntu/go/src/github.com/presbrey/goraptor/goraptor.go:838 +0x244
created by github.com/presbrey/goraptor.(*Parser).Parse
	/home/ubuntu/go/src/github.com/presbrey/goraptor/goraptor.go:842 +0x168

goroutine 1 [IO wait, 4 minutes]:
net.(*pollDesc).Wait(0xc2080dcbc0, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080dcbc0, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080dcb60, 0x0, 0x7fd41751cc70, 0xc20810bc60)
	/usr/lib/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208036018, 0xc2080f5c20, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208036018, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:244 +0x4c
crypto/tls.(*listener).Accept(0xc2081234a0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/tls.go:46 +0x6b
net/http.(*Server).Serve(0xc208044300, 0x7fd41751f240, 0xc2081234a0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:1728 +0x92
main.main()
	/home/ubuntu/go/src/github.com/linkeddata/gold/server/daemon.go:166 +0x121e

goroutine 17 [syscall, 241 minutes, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3052 [IO wait, 4 minutes]:
net.(*pollDesc).Wait(0xc2080e8290, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080e8290, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080e8230, 0xc208209000, 0x800, 0x800, 0x0, 0x7fd41751cc70, 0xc20814a190)
	/usr/lib/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080360a0, 0xc208209000, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20826a570, 0x7fd41751f400, 0xc2080360a0, 0x5, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc208196000, 0x17, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc208196000, 0xc20817b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:904 +0x166
net/http.(*liveSwitchReader).Read(0xc2080f02c8, 0xc20817b000, 0x1000, 0x1000, 0x8, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc2081b6fe0, 0xc20817b000, 0x1000, 0x1000, 0x800, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc2081ca3c0)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc2081ca3c0, 0xc20826a60a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc2081ca3c0, 0x0, 0x0, 0x0, 0xc20826a600, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc2082302a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc2082302a0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc2081ca3c0, 0xc2080fb110, 0x0, 0x0)
	/usr/lib/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc2080f0280, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc2080f0280)
	/usr/lib/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1751 +0x35e

goroutine 15 [IO wait, 210 minutes]:
net.(*pollDesc).Wait(0xc2080e40d0, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080e40d0, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080e4070, 0xc208159800, 0x800, 0x800, 0x0, 0x7fd41751cc70, 0xc2080f8df8)
	/usr/lib/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208036030, 0xc208159800, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20807cc00, 0x7fd41751f400, 0xc208036030, 0x5, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc208091080, 0x17, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc208091080, 0xc20814e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:904 +0x166
net/http.(*liveSwitchReader).Read(0xc2080f00e8, 0xc20814e000, 0x1000, 0x1000, 0xc20811a360, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc208112080, 0xc20814e000, 0x1000, 0x1000, 0xc207ff84ce, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc2080441e0)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadByte(0xc2080441e0, 0xc20807b310, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:196 +0x86
golang.org/x/net/websocket.hybiFrameReaderFactory.NewFrameReader(0xc2080441e0, 0x7fd417521370, 0xc20807b310, 0x0, 0x0)
	/home/ubuntu/go/src/golang.org/x/net/websocket/hybi.go:126 +0xd6
golang.org/x/net/websocket.Codec.Receive(0x992eb8, 0x992ec0, 0xc208156990, 0x7443a0, 0xc2080f8d90, 0x0, 0x0)
	/home/ubuntu/go/src/golang.org/x/net/websocket/websocket.go:314 +0x18b
github.com/linkeddata/gold.websocketHandler(0xc208156990)
	/home/ubuntu/go/src/github.com/linkeddata/gold/websocket.go:34 +0xc5
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x992ea0, ...)
	/home/ubuntu/go/src/golang.org/x/net/websocket/server.go:90 +0x292
golang.org/x/net/websocket.Handler.ServeHTTP(0x992e50, 0x7fd417520b68, 0xc208106460, 0xc208032820)
	/home/ubuntu/go/src/golang.org/x/net/websocket/server.go:113 +0x8a
github.com/linkeddata/gold.websocketServe(0x7fd417520b68, 0xc208106460, 0xc208032820)
	/home/ubuntu/go/src/github.com/linkeddata/gold/websocket.go:92 +0x48
github.com/linkeddata/gold.(*Server).ServeHTTP(0xc20807a370, 0x7fd417520b68, 0xc208106460, 0xc208032820)
	/home/ubuntu/go/src/github.com/linkeddata/gold/server.go:205 +0x426
net/http.serverHandler.ServeHTTP(0xc208044300, 0x7fd417520b68, 0xc208106460, 0xc208032820)
	/usr/lib/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2080f00a0)
	/usr/lib/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1751 +0x35e

goroutine 3051 [IO wait, 4 minutes]:
net.(*pollDesc).Wait(0xc2080e80d0, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080e80d0, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080e8070, 0xc208153800, 0x400, 0x400, 0x0, 0x7fd41751cc70, 0xc2080f9920)
	/usr/lib/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208036060, 0xc208153800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20826ae40, 0x7fd41751f400, 0xc208036060, 0x5, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc208091340, 0x17, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc208091340, 0xc2081fc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:904 +0x166
net/http.(*liveSwitchReader).Read(0xc2080f0048, 0xc2081fc000, 0x1000, 0x1000, 0x8, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc2081b6040, 0xc2081fc000, 0x1000, 0x1000, 0x800, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc2081ca000)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc2081ca000, 0xc20826a10a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc2081ca000, 0x0, 0x0, 0x0, 0xc20826a100, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc20826af30, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc20826af30, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc2081ca000, 0xc2080faea0, 0x0, 0x0)
	/usr/lib/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc2080f0000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc2080f0000)
	/usr/lib/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1751 +0x35e

goroutine 620 [IO wait, 209 minutes]:
net.(*pollDesc).Wait(0xc2080c60d0, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080c60d0, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080c6070, 0xc20817f000, 0x800, 0x800, 0x0, 0x7fd41751cc70, 0xc2081d5910)
	/usr/lib/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208036130, 0xc20817f000, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20818a4e0, 0x7fd41751f400, 0xc208036130, 0x5, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc208091600, 0x17, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc208091600, 0xc20819e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:904 +0x166
net/http.(*liveSwitchReader).Read(0xc208110048, 0xc20819e000, 0x1000, 0x1000, 0xc20811bb00, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc2081943a0, 0xc20819e000, 0x1000, 0x1000, 0xc207ff85ff, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc20819c480)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadByte(0xc20819c480, 0xc20807a000, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:196 +0x86
golang.org/x/net/websocket.hybiFrameReaderFactory.NewFrameReader(0xc20819c480, 0x7fd417521370, 0xc20807a000, 0x0, 0x0)
	/home/ubuntu/go/src/golang.org/x/net/websocket/hybi.go:126 +0xd6
golang.org/x/net/websocket.Codec.Receive(0x992eb8, 0x992ec0, 0xc208042b40, 0x7443a0, 0xc208189440, 0x0, 0x0)
	/home/ubuntu/go/src/golang.org/x/net/websocket/websocket.go:314 +0x18b
github.com/linkeddata/gold.websocketHandler(0xc208042b40)
	/home/ubuntu/go/src/github.com/linkeddata/gold/websocket.go:34 +0xc5
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x992ea0, ...)
	/home/ubuntu/go/src/golang.org/x/net/websocket/server.go:90 +0x292
golang.org/x/net/websocket.Handler.ServeHTTP(0x992e50, 0x7fd417520b68, 0xc2081103c0, 0xc2080325b0)
	/home/ubuntu/go/src/golang.org/x/net/websocket/server.go:113 +0x8a
github.com/linkeddata/gold.websocketServe(0x7fd417520b68, 0xc2081103c0, 0xc2080325b0)
	/home/ubuntu/go/src/github.com/linkeddata/gold/websocket.go:92 +0x48
github.com/linkeddata/gold.(*Server).ServeHTTP(0xc20807a370, 0x7fd417520b68, 0xc2081103c0, 0xc2080325b0)
	/home/ubuntu/go/src/github.com/linkeddata/gold/server.go:205 +0x426
net/http.serverHandler.ServeHTTP(0xc208044300, 0x7fd417520b68, 0xc2081103c0, 0xc2080325b0)
	/usr/lib/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208110000)
	/usr/lib/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1751 +0x35e

goroutine 3311 [IO wait, 4 minutes]:
net.(*pollDesc).Wait(0xc2080e81b0, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080e81b0, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080e8150, 0xc20810d800, 0x800, 0x800, 0x0, 0x7fd41751cc70, 0xc20814a2b0)
	/usr/lib/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208036188, 0xc20810d800, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc208131e30, 0x7fd41751f400, 0xc208036188, 0x5, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc2081a0000, 0x17, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc2081a0000, 0xc208119000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:904 +0x166
net/http.(*liveSwitchReader).Read(0xc2080f0908, 0xc208119000, 0x1000, 0x1000, 0xc00000000000008, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc208112b40, 0xc208119000, 0x1000, 0x1000, 0x800, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc2081161e0)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc2081161e0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc2081161e0, 0x0, 0x0, 0x0, 0xc207fe7500, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc20818a3c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc20818a3c0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc2081161e0, 0xc2080fa1a0, 0x0, 0x0)
	/usr/lib/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc2080f08c0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc2080f08c0)
	/usr/lib/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1751 +0x35e

goroutine 3082 [chan receive]:
github.com/linkeddata/gold.(*Graph).Parse(0xc20826ba70, 0x7fd4175264e8, 0xc20818c180, 0xc20814a080, 0xb)
	/home/ubuntu/go/src/github.com/linkeddata/gold/graph.go:254 +0x5bf
github.com/linkeddata/gold.(*Server).handle(0xc20807a370, 0x7fd417520b68, 0xc2080f06e0, 0xc20814a0c0, 0xc20826a270)
	/home/ubuntu/go/src/github.com/linkeddata/gold/server.go:1047 +0x1b765
github.com/linkeddata/gold.(*Server).ServeHTTP(0xc20807a370, 0x7fd417520b68, 0xc2080f06e0, 0xc208033380)
	/home/ubuntu/go/src/github.com/linkeddata/gold/server.go:212 +0x518
net/http.serverHandler.ServeHTTP(0xc208044300, 0x7fd417520b68, 0xc2080f06e0, 0xc208033380)
	/usr/lib/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2080f0500)
	/usr/lib/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1751 +0x35e

goroutine 3053 [IO wait]:
net.(*pollDesc).Wait(0xc2080e8300, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080e8300, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080e82a0, 0xc208209800, 0x800, 0x800, 0x0, 0x7fd41751cc70, 0xc20814b120)
	/usr/lib/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080360a8, 0xc208209800, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20826a9c0, 0x7fd41751f400, 0xc2080360a8, 0x5, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc2081962c0, 0x17, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc2081962c0, 0xc20815b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:904 +0x166
net/http.(*liveSwitchReader).Read(0xc2080f0368, 0xc20815b000, 0x1000, 0x1000, 0x8, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc2081b7020, 0xc20815b000, 0x1000, 0x1000, 0x800, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc2081ca420)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc2081ca420, 0xc20826aa0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc2081ca420, 0x0, 0x0, 0x0, 0xc20826aa00, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc20810e120, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc20810e120, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc2081ca420, 0xc208033520, 0x0, 0x0)
	/usr/lib/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc2080f0320, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc2080f0320)
	/usr/lib/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1751 +0x35e

goroutine 3513 [IO wait, 4 minutes]:
net.(*pollDesc).Wait(0xc2080e9e90, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080e9e90, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080e9e30, 0xc20815d400, 0x400, 0x400, 0x0, 0x7fd41751cc70, 0xc2080f83e8)
	/usr/lib/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080362c8, 0xc20815d400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20810e060, 0x7fd41751f400, 0xc2080362c8, 0x5, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc2081a18c0, 0x17, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc2081a18c0, 0xc208193000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:904 +0x166
net/http.(*liveSwitchReader).Read(0xc2080f1268, 0xc208193000, 0x1000, 0x1000, 0xc20811a6c0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc208113820, 0xc208193000, 0x1000, 0x1000, 0xc207ff85d2, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc2080f5c20)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadByte(0xc2080f5c20, 0xc20807a2d0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:196 +0x86
golang.org/x/net/websocket.hybiFrameReaderFactory.NewFrameReader(0xc2080f5c20, 0x7fd417521370, 0xc20807a2d0, 0x0, 0x0)
	/home/ubuntu/go/src/golang.org/x/net/websocket/hybi.go:126 +0xd6
golang.org/x/net/websocket.Codec.Receive(0x992eb8, 0x992ec0, 0xc208096120, 0x7443a0, 0xc2080f8380, 0x0, 0x0)
	/home/ubuntu/go/src/golang.org/x/net/websocket/websocket.go:314 +0x18b
github.com/linkeddata/gold.websocketHandler(0xc208096120)
	/home/ubuntu/go/src/github.com/linkeddata/gold/websocket.go:34 +0xc5
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x992ea0, ...)
	/home/ubuntu/go/src/golang.org/x/net/websocket/server.go:90 +0x292
golang.org/x/net/websocket.Handler.ServeHTTP(0x992e50, 0x7fd417520b68, 0xc2080f0c80, 0xc2080fa410)
	/home/ubuntu/go/src/golang.org/x/net/websocket/server.go:113 +0x8a
github.com/linkeddata/gold.websocketServe(0x7fd417520b68, 0xc2080f0c80, 0xc2080fa410)
	/home/ubuntu/go/src/github.com/linkeddata/gold/websocket.go:92 +0x48
github.com/linkeddata/gold.(*Server).ServeHTTP(0xc20807a370, 0x7fd417520b68, 0xc2080f0c80, 0xc2080fa410)
	/home/ubuntu/go/src/github.com/linkeddata/gold/server.go:205 +0x426
net/http.serverHandler.ServeHTTP(0xc208044300, 0x7fd417520b68, 0xc2080f0c80, 0xc2080fa410)
	/usr/lib/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2080f1220)
	/usr/lib/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1751 +0x35e
exit status 2

**Comment by deiu** [comment]
What lib raptor version is currently installed on that machine?

**Comment by melvincarvalho** [comment]
Actually I just did a git pull on https://github.com/presbrey/goraptor/blob/master/goraptor.go

That fixed it!
