### ISSUE TITLE
POST new resource appears not to trigger pub of the LDPC that created it

### ISSUE THREAD

**Issue by melvincarvalho** [linkeddata/gold#43]
looking at server.go line 973, on a POST it sends resource.URI to the websocket

https://github.com/linkeddata/gold/blob/master/server.go#L973

but resource.URI seems to be the new resource, rather than, the LDPC
 
so I think that resources that are subscribed to the container wont see a sub

id be happy to patch it, any thoughts on the best way?

**Comment by melvincarvalho** [comment]
I think it happens here:

https://github.com/linkeddata/gold/blob/master/server.go#L864

    resource, err = s.pathInfo(resource.Base + "/" + resource.Path)

The original resource gets overwritten with the newly created

**Comment by deiu** [comment]
Thanks! I'll look into it.

**Comment by melvincarvalho** [comment]
Possible suggestion

set updateURI := resource.URI ( L757 )

at start of POST, then

onUpdateURI(updateURI) ( L973 )

Not sure how well that fits with the current structure tho, I can put in a PR if that seems like a workable fix.
