### ISSUE TITLE
Add a standard way to logout

### ISSUE THREAD

**Issue by reederz** [linkeddata/gold#45]
It seems like there's a lot of fuss about logging out with client certificates. E.g.
- https://stackoverflow.com/questions/10487205/https-client-certificate-logout-relogin
- https://code.google.com/p/chromium/issues/detail?id=90676

It would really cool if there was an API endpoint for that on gold so that we don't have to come up with various client side hacks.

**Comment by deiu** [comment]
It's not that simple, because the client certificate "login" step takes place in the browser. I don't think we can fix this issue in gold.

**Comment by reederz** [comment]
OK. What would you suggest instead?

**Comment by deiu** [comment]
It's something only the browser vendors can fix. AFAIK, Firefox and IE offer an API to allow apps to unregister a selected client cert. Chrome and Safari don't.

**Comment by akuckartz** [comment]
Maybe @bblfish has some suggestions ?

**Comment by bblfish** [comment]
yep, that's a browser API thing. @reederz told me firefox no longer supports logout, which is sad if true. On the other hand Google Chrome supports personas.
