### ISSUE TITLE
Flag provided but not defined: -https

### ISSUE THREAD

**Issue by nicola** [linkeddata/gold#49]
I get this when following the README.md

```
$ ~/go/bin/server -https=":8443" -root=/User/ldp/ -debug
```

**Comment by deiu** [comment]
Oops. I think you need to provide the -http flag too. I fixed the README now.

**Comment by nicola** [comment]
I solve by using -bind (I think)

**Comment by deiu** [comment]
You must have a really old version of gold. Bind doesn't exist anymore.
