### ISSUE TITLE
PATCHes which conflict should return "409 Conflict"

### ISSUE THREAD

**Issue by timbl** [linkeddata/gold#53]
I am finding that with gold (databox.me) I am getting a strange error on the client side, "I managed to do the patch you wanted in the server, but the statement you wanted to delete doesn't exist in my local store copy." This I suspects points to the store not properly rejecting with 409 a PATCH whose delete fails. This problem does not happen with ldnode. I am using a linked list, and patching things into the list, only to find the link I was going to replace has gone.

(I don't have an isolated test, but the app I was a using was
https://timbl.databox.me/Public/2015/test/index.html
When hthe client JS console "Uncaught TypeError: Cannot read property 'subject' of undefined" this is because in fact the deleted statement was not in the store. New veresions will have a more explicit exception text)

The problem does not happen with ldnode, though it could be that as ldnode does not support websockets it seems there is less asynchronous activity in the app

**Comment by melvincarvalho** [comment]
I havent yet been able to replicate this.  

when I try it in two browsers, the change is propagated to the 2nd browser but the line becomes greyed out.  There error I get is not a 409 but:

    Uncaught Statement to be removed is not on store: <https://timbl.databox.me/Public/2015/test/results.ttl#id1443027571303> <http://rdfs.org/sioc/ns#content> "g" .
    $rdf.IndexedFormula.$rdf.IndexedFormula.removeMatch 
    @ mashlib-alpha.js:4191(anonymous function) 
    @ mashlib-alpha.js:6259$rdf.sparqlUpdate.sparql._fire.xhr.onreadystatechange 
    @ mashlib-alpha.js:6112

**Comment by timbl** [comment]
I think you replicated it.    "Statement to be removed is not on store:" means "When I went to mirror in my local store the change I asked the server to make, I could not, as the server and localstore have got out of sync.   It looks as though one operation replaced "g" with "go" (or something) and another tried at the same time to replace "g" with "ga".  One of them should have failed 409, in which case the server store and the localstore would have stayed in sync.  

I have found that the linked lists on the gold version get inconsistent (like >1 head) while on the ldnode they don't.   The code adds new lines by unhooking the  link from the last line to the hub and replacing it with two links one from that last line to a new line and one from the new line to he hub.  When this is done without 409 protection, you get the same sort of error that the original link can't be deleted in the local store.

The bug is that the server SHOULD give 409 but does not, when asked to delete something which does not exist in a patch.

**Comment by timbl** [comment]
In https://github.com/linkeddata/gold/blob/master/sparqlupdate.go 

		case "DELETE", "DELETE DATA":
			for pattern := range query.graph.IterTriples() {
				for _, triple := range g.All(pattern.Subject, pattern.Predicate, nil) {
					if pattern.Object.Equal(triple.Object) {
						g.Remove(triple)
					}
				}
			}
		}
The DELETE MUST be done before the INSERT and the INSERT MUST BE done ONLY if the delete succeeds.

**Comment by deiu** [comment]
Thanks for opening this issue! I'll get on it asap.

**Comment by deiu** [comment]
Fixed in 61a9dda80f954709e4310ec6ef53f29a8aa697c1
