### ISSUE TITLE
Account Recovery: Generate new WebID

### ISSUE THREAD

**Issue by almereyda** [linkeddata/gold#68]
Due to the very minimal interface when following the account retrieval token https://almereyda.databox.me/,system/accountRecovery?token= , I seem to be unable to generate a new WebID with Firefox 43 by providing my name `jon richter` and the WebID https://almereyda.databox.me/ which I intended to reclaim.

https://almereyda.databox.me/,system/newCert then answers with

    open /gold-data/almereyda.databox.me/: is a directory

whilst the HTTPS endpoint at `/dns/me/databox/almereyda/` still yields 403.

**Comment by deiu** [comment]
Thanks for letting us know. I'll take a look.

**Comment by melvincarvalho** [comment]
Your WebID is : 

    https://almereyda.databox.me/profile/card#me

I typed that into the box and it gave the message:

    You should receive an email shortly, with further instructions.

**Comment by yalamerde** [comment]
Thanks, the card's Hash URL solved it. Then as an IndieWebber it was just confusing "Account recovery" knew how to fall back to E-Mail to reach me without the `profile/card#me` slug initially.

Interestingly I've never received said third party Recovery instructions from just above.

**Comment by dmitrizagidulin** [comment]
Extracting the various issues from this discussion to [solid/solid/19 - Document/Improve Account Recovery Workflow](https://github.com/solid/solid/issues/19). Closing this one (no further action items on here).
