### ISSUE TITLE
Mechanism to upgrade insecure requests

### ISSUE THREAD

**Issue by csarven** [linkeddata/gold#70]
https://www.w3.org/TR/upgrade-insecure-requests/ puts forward "a mechanism which allows authors to instruct a user agent to upgrade a priori insecure resource requests to secure transport before fetching them."

This is a handy feature to get around some of the mixed content issues.

**Comment by dmitrizagidulin** [comment]
Moving to https://github.com/solid/solid-spec/issues/73

**Comment by dmitrizagidulin** [comment]
Issue moved, closing.
