### ISSUE TITLE
Account Recovery

### ISSUE THREAD

**Issue by ghost** [linkeddata/gold#74]
New Laptop.  Attempted to recover account (issue new cert). i was sent an email with a link. Clicked on it. It asked my Name / WebID, entered the information then seemingly nothing happened.

Using Chrome on OSX.

**Comment by deiu** [comment]
Did you provide an email when you first signed up?

**Comment by melvincarvalho** [comment]
Hi @ghost want to try this again at :  

https://gitter.im/solid/chat

Works best in firefox.  Closing issue as its over 1 year old, and it would be easier to help you in chat ...
