### ISSUE TITLE
docker image doesn't start

### ISSUE THREAD

**Issue by markwilkinson** [linkeddata/gold#85]
$ sudo docker run -p ***.***.***.***:8080:443 linkeddata/gold
[debug] 2017/06/30 12:13:52 server.go:180: ---- starting server ----
[debug] 2017/06/30 12:13:52 server.go:181: config: &gold.ServerConfig{ListenHTTP:":80", ListenHTTPS:":443", WebIDTLS:true, TLSCert:"", TLSKey:"", DataRoot:"/data/", Vhosts:false, Insecure:false, NoHTTP:false, HSTS:true, Debug:true, CookieAge:24, TokenAge:5, MetaSuffix:",meta", ACLSuffix:",acl", DataApp:"tabulator", DirApp:"http://linkeddata.github.io/warp/#list/", SignUpApp:"https://solid.github.io/solid-signup/?domain=", ProxyTemplate:"", ProxyLocal:true, QueryTemplate:"", DirIndex:[]string{"index.html", "index.htm"}, DiskLimit:100000000, Agent:"", Salt:"", BoltPath:"", SMTPConfig:gold.EmailConfig{Name:"", Addr:"", User:"", Pass:"", Host:"", Port:0, ForceSSL:false, Insecure:false}}
2017/06/30 12:13:52 daemon.go:156: open : no such file or directory

Any idea what it is trying and failing to open?

Cheers!

**Comment by deiu** [comment]
Hi Mark, I just took a look and it seems that the Dockerfile we use to build the image did not set a TMPDIR value. I've pushed a patch that should fix it. Please pull the updated image as soon as it's done building.
