### ISSUE TITLE
gold is accessible by IP address, but not domain name

### ISSUE THREAD

**Issue by markwilkinson** [linkeddata/gold#86]
Title says it all.  

If I run a normal webserver on that domain and port (80), I can reach it using either the IP address or the domain name (via http, I haven't tried https).  If I run the gold Docker image, I can reach the server via https://IP:port but not https://Domain:port  (domain:port pops up a little "rocket" icon with a 404 message)

Thoughts? 

Mark

**Comment by deiu** [comment]
Hi! I just tried locally and it worked. Did you try accessing `https://domain:port` directly? Since the server cert is self-signed, the browser may not want to connect to that server, so you need to manually say that you trust the cert when you first connect.

**Comment by markwilkinson** [comment]
Correct - I am able to access from command line tools (curl) when turning certificates off.

Thanks!

**Comment by aucampia** [comment]
@markwilkinson  is this still an issue?
