### ISSUE TITLE
Question: does GOLD support etag / If-match requests?

### ISSUE THREAD

**Issue by gklyne** [linkeddata/gold#95]
(I'm not a Go programmer, so I'm not sure if this is a GOLD issue or a Go HTTP issue.  Pointers to information gratefully received.)

(a) does GOLD provide `etag` values in its responses?

and 

(b) can HTTP `If-match` headers be used with responses to allow applications to respond appropriately to concurrent update requests?

This is specifically to do with using PUT to update/replace identified resources within an LDP container.  (Looking at some other issues, I think the answer is yes to both, but I'm seeking confirmation.)

**Comment by deiu** [comment]
Hi,

Yes to both questions. :)

**Comment by gklyne** [comment]
Thanks! :)
